@Bank.API_HostAddress = http://localhost:5020

GET {{Bank.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Bank.API_HostAddress}}/weatherforecast/
Accept: application/json

{
  "firstName": "string",
  "lastName": "string",
  "patronymic": "string",
  "passportSeries": "1234",
  "passportNumber": "222266",
  "registrationDateYear": 2002,
  "registrationDateMonth": 8,
  "registrationDateDay": 22,
  "region": "string",
  "city": "string",
  "street": "string",
  "houseNumber": 0,
  "buildingNumber": "string",
  "phoneNumber": "string"
}