@Bank.API_HostAddress = http://localhost:5020

GET {{Bank.API_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIrNzExMSIsIm5iZiI6MTcxNjU2OTA3NSwiZXhwIjoxNzE2NjE5NDc1LCJpYXQiOjE3MTY1NjkwNzV9.N73NZP4oRBYhHZzq1rXdnZj9mk49AWlTdetRpubbNuCxGPfy1Zx9-vVu5gT6jU6ywD8rPwJFCnGSKBgRAcN2WA
###

POST {{Bank.API_HostAddress}}/weatherforecast/
//Accept: application/json

{
  "firstName": "string",
  "lastName": "string",
  "patronymic": "string",
  "passportSeries": "1234",
  "passportNumber": "222266",
  "registrationDateYear": 2002,
  "registrationDateMonth": 8,
  "registrationDateDay": 22,
  "region": "string",
  "city": "string",
  "street": "string",
  "houseNumber": 0,
  "buildingNumber": "string",
  "phoneNumber": "string"
}


###