@Bank.API_HostAddress = http://localhost:5020

GET {{Bank.API_HostAddress}}/weatherforecast/
Accept: application/json
Cookie: Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIrNzExMSIsIm5iZiI6MTcxNjU2NTQwMSwiZXhwIjoxNzE2NjE1ODAxLCJpYXQiOjE3MTY1NjU0MDF9.PcwJNTc_nRxjr8ZBJIOtrPKHUEppYV8ahjXNpvUsq1eXiKYlomVaA-O6_gK78KcNBHKCfxk6yVWSy0PbsESjeQ

###

POST {{Bank.API_HostAddress}}/weatherforecast/
//Accept: application/json

{
  "firstName": "string",
  "lastName": "string",
  "patronymic": "string",
  "passportSeries": "1234",
  "passportNumber": "222266",
  "registrationDateYear": 2002,
  "registrationDateMonth": 8,
  "registrationDateDay": 22,
  "region": "string",
  "city": "string",
  "street": "string",
  "houseNumber": 0,
  "buildingNumber": "string",
  "phoneNumber": "string"
}


###